name: coords
version: '${project.version}'
main: me.patunki.coords.Coords
api-version: '1.20'

authors: [ Patunki ]
commands:
  t채ss채:
    description: Listaa tallennetut sijainnit.
    usage: /<command> [message]
  miss채:
    description: N채kee listan tallennetuista sijanneista.
    usage: /<command>
  apua:
    description: Apua.
    usage: /<command>

