name: CoordsPlugin
version: '${project.version}'
main: coordsplugin.coordsplugin.CoordsPlugin
api-version: 1.19
authors: [ C0reB ]
commands:
  t채ss채:
    description: Listaa tallennetut sijainnit.
    usage: /<command> [message]
  miss채:
    description: N채kee listan tallennetuista sijanneista.
    usage: /<command>

